version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - symfony_network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://symfony:symfony@database:5432/symfony?serverVersion=15&charset=utf8
    networks:
      - symfony_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.symfony.rule=Host(`symfony.localhost`)"
      - "traefik.http.services.symfony.loadbalancer.server.port=9000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`symfony.localhost`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - symfony_network

  adminer:
    image: adminer
    networks:
      - symfony_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.localhost`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"

  node:
    image: node:20-alpine
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: ["sh", "-c", "npm install && npm run watch"]
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  db_data:
